### ISSUE TITLE
Content inside Hints does not seem to be clickable

### ISSUE THREAD

**Issue by OrKoN** [uber/react-vis#112]
Hi,

I tried to put an a tag into a Hint but it is not clickable. It looks like react-vis captures all click events from inside the Hints. Is there a way to make smth inside a Hint clickable?

Best regards,
Alex

**Comment by bulyonov** [comment]
@OrKoN It was intentional that the component will not be clickable, however, you can easily enable that by overriding `.rv-crosshair` and `.rv-hint` CSS classes:

```scss
.rv-crosshair, .rv-hint {
  pointer-events: auto;
}
```
